CREATE TABLE TERMINAL(
OID_TERMINAL NUMBER(10),
OID_USER NUMBER(10),
CUIT NUMBER(10) NOT NULL,
DESCRIPCION VARCHAR(30) NOT NULL,
DIRECCION VARCHAR(30) NOT NULL,
ESTADO NUMBER(1) NOT NULL 
 
 );

 ALTER TABLE TERMINAL 
 ADD 
 CONSTRAINT  oid_terminal_pk PRIMARY KEY (OID_TERMINAL); 
 
 ALTER TABLE TERMINAL
 ADD 
 CONSTRAINT oid_user_fk FOREIGN KEY (OID_USER)
 REFERENCES CUENTA(OID_USER);