CREATE TABLE SUBE ( 
     OID_SUBE NUMBER(10),
    COPIA_SALDO NUMBER(10,2),
    ESTADO NUMBER(1),
    NUMERO_SUBE NUMBER (10)
    );
    
    
  ALTER TABLE SUBE
 ADD   CONSTRAINT oid_sube_pk PRIMARY KEY(OID_SUBE);
 
 ALTER TABLE SUBE
ADD CONSTRAINT numero_sube_uk UNIQUE (NUMERO_SUBE);  
 